services:
  ora:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: ora
    environment:
      - ORACLE_PWD=${DB_PASSWORD}
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - oracle_backup:/opt/oracle/backup
    restart: unless-stopped
    networks:
      - app-network
    labels:
      - "oracle=true" # Oracle 컨테이너 식별용
      - "backup=critical" # 중요 데이터 표시

  tjspring:
    image: obama1004/tjspring:latest
    container_name: tjspring
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - SERVER_PORT=8081
    ports:
      - "8080:8080"
    depends_on:
      - ora
    restart: unless-stopped
    networks:
      - app-network

  studyo:
    image: obama1004/studyo:latest
    container_name: studyo
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://yourdomain.com/api
    depends_on:
      - tjspring
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - studyo
      - tjspring
    restart: unless-stopped
    networks:
      - app-network

volumes:
  oracle_data:
  oracle_backup:

networks:
  app-network:
    driver: bridge
