name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "배포 사유"
        required: false
        default: "React studyo & SpringBoot 배포"

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker images
        run: |
          # studyo (React + NGINX)
          docker build -t obama1004/studyo:latest ./frontend
          docker push obama1004/studyo:latest

          # tjspring (Spring Boot)
          docker build -t obama1004/tjspring:latest ./backend
          docker push obama1004/tjspring:latest

      # EC2 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntuss
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu

            # .env 파일 생성
            cat > .env <<-'EOF'
              DB_URL=${{ secrets.DB_URL }}
              DB_USERNAME=${{ secrets.DB_USERNAME }}
              DB_PASSWORD=${{ secrets.DB_PASSWORD }}
              AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_REGION=${{ secrets.AWS_REGION }}
            EOF

            # 기존 애플리케이션 컨테이너 중지 및 제거
            docker stop studyo tjspring 2>/dev/null || true
            docker rm -f studyo tjspring 2>/dev/null || true

            # 최신 이미지 Pull
            docker pull obama1004/studyo:latest
            docker pull obama1004/tjspring:latest

            # 애플리케이션 컨테이너만 실행 (Oracle은 건드리지 않음)
            docker compose up -d --no-recreate --no-deps studyo tjspring
