name: CI/CD Pipeline (HTTPS)

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "배포 사유"
        required: false
        default: "React studyo & SpringBoot 배포 (HTTPS)"

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      # 1. 코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Docker Hub 로그인
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Docker 이미지 Pull (애플리케이션만)
      - name: Pull Docker Images
        run: |
          docker compose -f docker-compose.yml pull tjspring studyo

      # 4. EC2 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu

            # .env 파일 생성
            cat > .env <<EOF
            DB_URL=${{ secrets.DB_URL }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION=${{ secrets.AWS_REGION }}
            VITE_HTTPS=true
            VITE_SSL_KEY_PATH=/etc/letsencrypt/live/www.studyo.r-e.kr/privkey.pem
            VITE_SSL_CERT_PATH=/etc/letsencrypt/live/www.studyo.r-e.kr/fullchain.pem
            EOF

            # 기존 애플리케이션 컨테이너 중지 및 제거 (DB는 그대로)
            docker stop tjspring studyo 2>/dev/null || true
            docker rm -f tjspring studyo 2>/dev/null || true

            # 최신 이미지 다운로드
            docker compose pull tjspring studyo

            # 애플리케이션 컨테이너 실행 (HTTPS 적용)
            docker compose up -d --no-recreate --no-deps tjspring studyo
