name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "수동 배포 사유"
        required: false
        default: "React studyo & SpringBoot 배포"

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push with Docker Compose
        run: |
          docker compose build
          docker compose push

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu

            # 최신 이미지 pull
            docker compose pull

            # studyo, tjspring 컨테이너만 재배포
            docker compose up -d --force-recreate --no-deps tjspring studyo

            # 사용하지 않는 이미지 정리
            docker image prune -f
