name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "배포 사유"
        required: false
        default: "React studyo & SpringBoot 배포"

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push with Docker Compose
        run: |
          # 캐시 없이 최신 이미지 빌드
          docker compose build --no-cache

          # Git SHA 태그 추가 (고유 버전)
          export GIT_SHA=${GITHUB_SHA::7}
          docker tag obama1004/studyo:latest obama1004/studyo:$GIT_SHA
          docker tag obama1004/tjspring:latest obama1004/tjspring:$GIT_SHA

          # Docker Hub로 push
          docker compose push
          docker push obama1004/studyo:$GIT_SHA
          docker push obama1004/tjspring:$GIT_SHA

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu

            # 최신 이미지 pull
            docker compose pull

            # Secrets 기반 환경변수 적용 후 컨테이너 재배포
            DB_USERNAME=${{ secrets.DB_USERNAME }} DB_PASSWORD=${{ secrets.DB_PASSWORD }} docker compose up -d --force-recreate --no-deps studyo tjspring

            # 사용하지 않는 이미지 제거
            docker image prune -f
