- name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            # docker-compose가 설치되어 있지 않으면 설치
            if ! command -v docker-compose &> /dev/null
            then
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # docker-compose.yml 파일이 있는 디렉토리로 이동
            cd /home/ubuntu
            
            # 기존 컨테이너를 모두 중지하고 삭제
            sudo docker-compose down
            
            # 최신 이미지 pull
            sudo docker-compose pull
            
            # 모든 컨테이너를 다시 시작 (백그라운드에서 실행)
            sudo docker-compose up -d
            
            # 사용하지 않는 이미지 정리
            sudo docker image prune -f